### ISSUE TITLE
Missing paper.journal attribute

### ISSUE THREAD

**Issue by SimonJMurphy** [andycasey/ads#111]
## Expected Behavior
In the same way that one can do
`paper.title`
one should also be able to do
`paper.journal`

## Possible Solution
Since it is already possible to get the bibcode of the paper and this contains the abbreviated journal name, then a handy workaround would be:
`bibcode.split(".")[0][4:]`
This takes the bibcode content before the first '.', and removes the first four characters (the year), leaving the journal name.

## Your Environment
* Version used 0.12.3
* Python version 3.6.7

**Comment by andycasey** [comment]
👋🏻 @SimonJMurphy 

This is a great idea! I have implemented it in version `v1`. It meant a little bit more code than just `bibcode.split(".")[0][4:]`, but maybe that's because I over-engineered it. Or because I write bad code. Or both.

You can read the documentation on this new feature [here](https://ads.readthedocs.io/en/v1/models/journal.html), where I have attributed you at the bottom.

And happy birthday for next Monday 🥳 🍰
