### ISSUE TITLE
Missing .adsurl attribute

### ISSUE THREAD

**Issue by SimonJMurphy** [andycasey/ads#112]
## Expected Behavior
In the same way that one can do
`paper.bibcode`
one should also be able to do
`paper.adsurl`

## Possible Solution
Since the adsurl is formulated by taking the standard ADS domain (prefix) then appending the bibcode, it is possible to recreate the URL from this bibcode:
`def adsurl(bibcode):`
`return 'https://ui.adsabs.harvard.edu/abs/' + bibcode`

## Your Environment
* Version used 0.12.3
* Python version 3.6.7

**Comment by andycasey** [comment]
If it were *only* the ADS URL that people would ever be accessing then I could be persuaded that it was worth having as an attribute of `paper` (or `ads.Document`), but each record in ADS has a long list of external resources that are accessible through different URLs. But these don't all exist for every record: sometimes a record will have a link for external "data" resources, and another record won't. Since the ADS URL is always that same format, I think it's probably a bit superfluous to have this as an attribute of `paper` (or `ads.Document`).

The [resolver service](https://ads.readthedocs.io/en/v1/services/resolver.html) can provide links to external resources for an ADS record.

Thanks for the suggestion! 🍰 🥳 🎈
