### ISSUE TITLE
readthedocs rendering is broken

### ISSUE THREAD

**Issue by zingale** [andycasey/ads#116]
## Expected Behavior

https://ads.readthedocs.io/en/latest/

it looks like maybe a style sheet is missing? perhaps due to sphinx updates?

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used (hint: `python -c "import ads; print(ads.__version__)"`)
* Python version (hint: `python -V`)

**Comment by andycasey** [comment]
It's possible that the style sheet (and other items) are being blocked by your ad blocker because "ads" sounds a lot like (ad)vertisement(s). 

Recently I have been working on an updated version of this package, and ad blockers prevent stylesheets from loading on the documentation for that version (https://ads.readthedocs.io/en/v1/). 

Can you disable any ad blockers and try again?

**Comment by zingale** [comment]
oh you're right.  Such unfortunate naming issues.
