### ISSUE TITLE
qmetrics: metrics also possible with query

### ISSUE THREAD

**Issue by jhpoosthoek** [andycasey/ads#17]
I'm interested in the amount of papers published on a certain subject. 

Just to let you know to get this working I added a function called qmetrics to my installed core.py (and line 22 and __init__.py):

```python
def qmetrics(query, dates=None, database="astronomy or physics", rows=20,
    metadata=False):
    """ Retrieves metrics for a given query. """

    payload = _build_payload(query=query, database=database, rows=rows)
```

Only problem is that it gives an error when the return is zero. I'm currently using a try/except to catch that.

**Comment by andycasey** [comment]
Hi @jhpoosthoek 

Thanks for this. I will leave this open until a similar function can be properly incorporated into the new version of the code, which will use the updated ADS API.

**Comment by jhpoosthoek** [comment]
Hi Andy,

 

Sure, was just to let you know I was fiddling with your code ;-)

 

Cheers, Jelmer

**Comment by buist** [comment]
Hi Andy,

I used MetricsQuery to analyse a specific set of articles, but will it become possible to directly apply this on a query, instead of having to supply the bibcodes to MetricsQuery? This seems related to issue #8 

Many thanks!

Hans

**Comment by vsudilov** [comment]
Hi,

Currently the support for metrics is rudimentary -- there is the `MetricsQuery` interface that accepts a list of bibcodes, and there is a convenience `.metrics` property on every article (returned by a `SearchQuery`) that, when accessed, executes the metrics query on that individual bibcode.

Closing this issue since it's stale; if you'd like to continue the conversation or have a feature request/suggestion let's start a new issue and discuss.
