### ISSUE TITLE
Number of returned results doesn't correspond to 'rows' key value in SearchQuery

### ISSUE THREAD

**Issue by bruno-moraes** [andycasey/ads#28]
Example code:
````
In [5]: papers = ads.SearchQuery(q="supernova", sort="citation_count", rows=10)  
In [6]: print(len(list(papers)))
40
````
Not massively important, but a bit surprising anyway. Any explanation? Thanks!

**Comment by vsudilov** [comment]
Hi,

Nice observation, what's going on internally is a bit subtle:

`papers = ads.SearchQuery(...rows=10)` asks the ADS API to return 10 documents. These 10 documents are downloaded and put into the `papers` object immediately.

If you do `list(papers)`, it iterates over every document in that list. Once it hits the 10th one, it sees it needs to fetch more from the ADS API, since there are actually more than 10 documents that match that search `q`. It goes ahead and fetches the next 10, up to `4*rows` times for a total of 40 documents. That behaviour is configurable via the `max_pages` kwarg to `SearchQuery`.

It was designed this way so that people don't inadvertently ask the API for potentially millions of documents, which would also hose their daily query limits.

**Comment by andycasey** [comment]
Thanks for the explanation @vsudilov! I understand the pagination now, but I find this behaviour a little counter-intuitive, since the number of results to return is actually `rows+max_pages*rows`. With that said, I have no immediate solution that keeps normal behaviour with the pagination..

**Comment by bruno-moraes** [comment]
Ah, OK, understood! Maybe just documenting and/or renaming the key is enough? For example, I see that I can get my ten rows by setting max_pages to 0.

**Comment by cdeil** [comment]
I used `ads` for the first time 10 minutes ago and this is also the first confusing thing I ran into.
:+1:  to changing the arguments or at least writing some docs how this works.

**Comment by vsudilov** [comment]
It seems that the default behavior doesn't match expectations, namely that one expects `len(results) == rows`, if `rows` is specified.

To address that, what about just setting the default `max_rows` to match that expectation?
