### ISSUE TITLE
How to acknowledge use?

### ISSUE THREAD

**Issue by cdeil** [andycasey/ads#80]
How would you like the ADS Python package to be acknowledged?
Could you please spell that out in the README?

Maybe it's possible to get an entry in http://ascl.net/ or write a page or two for http://joss.theoj.org/ ?

I'm writing up an ADASS conference proceeding paper for a project where we're using this `ads` Python package extensively. Dor now I'm just putting a link to https://github.com/andycasey/ads . Please let me know if there's something else you prefer or if that is the best way.

**Comment by andycasey** [comment]
@vsudilov thoughts? Are there specific words/citations that ADS wants used to acknowledge explicit use of the API?

**Comment by vsudilov** [comment]
No strong opinions. @andycasey is the owner of the package, so I'll defer any opinions on how to cite to him.

Do note that this package doesn't have direct affiliation with ADS (both @jonnybazookatone and I no longer work there).  It's a purely community driven project :)

**Comment by jonnybazookatone** [comment]
@andycasey if you want to cite the ADS API, you can see the preferred text here: http://adsabs.github.io/help/terms/

>This research has made use of NASA’s Astrophysics Data System Bibliographic Services.

**Comment by andycasey** [comment]
@vsudilov and @jonnybazookatone: wow, I didn't know you guys weren't with ADS anymore 😦

@cdeil: I think for the moment just having a link to the repository is enough, and I'd also just include the specific ADS acknowledgement if you haven't already. Submitting something to ASCL or JOSS is a good idea, but it may have to wait for a hack week/end so that some other features can be implemented before submitting it somewhere.
