### ISSUE TITLE
Pre-requesting BibTeX field returns None

### ISSUE THREAD

**Issue by lowderchris** [andycasey/ads#82]
Over the years, my BibTeX library has been slowly mangled by using [Papers](http://papersapp.com). I've ended up with different styles of citekeys, and a host of other problems. I decided recently to take the nuclear option by managing my BibTeX library manually. Stumbling across this project was a boon, as I realized I could write up a simple Python script to take my existing database, grab the relevant bibcodes, and generate a clean database of BibTeX entries from ADS.

See my current attempt at https://github.com/lowderchris/ads-bib.

So, with a block of prose out of the way, I'm running into an issue with requesting the BibTeX data. I loop through a list of bibcodes, querying ADS as,

```python
q = list(ads.SearchQuery(bibcode=bc))
```

I can then throw these BibTeX entries to file with,

```python
with open('bib-lib.bib','a') as bibfile:
    for paper in q:
        print(paper.bibtex, file=bibfile)
```

While testing with a single bibcode, I noticed that it was flagging for lazily loading attributes, notably the BibTeX attribute. Helpfully, the README for this project had just the solution, so I appended the query as,

```python
q = list(ads.SearchQuery(bibcode=bc,fl=['author','title','bibtex']))
```

While running with this change, the code returned an BibTeX entry of 'None'. Without requesting the BibTeX entry beforehand, everything output as expected. I decided to ignore the warning temporarily, and run the script over a sample of about 200 bibcodes as a test. Unfortunately I'm somehow running into a 'Rate limit exceeded' issue now, even though querying with my API token returned ~4700 remaining inquiries out of 5000... So I can't debug any more at the moment (at least until midnight?), but I figured I would inquire here. Thanks in advance!

I'm using Python 3 for this bit of code.

**Comment by jonnybazookatone** [comment]
Glad to see you're using the ADS API and this client. Your issue is related to how the `bibtex` attribute behaves. When you do the following:
```python
paper.bibtex
```
it creates a request to the `/export` end point of the ADS API (see relevant lines [here](https://github.com/andycasey/ads/blob/master/ads/search.py#L284)).

This end point is different to the one accessed via the `SearchQuery` class (which is the `/search` end point). They both have different rate limits, and the `/export` end point is more strict, I can't remember exactly, but maybe 300.

What you should do instead is first collect the bibcodes you want to get the BibTeX for, and then send them in a list format to the `/export` end point, this way you can use a single request, rather than 1 per each paper. For example:

```python
q = ads.ExportQuery(bibcodes=['bib1', 'bib2', 'bib3'], format='bibtex')
bibtex = q.execute()
```
You can see how it's used in [this test](https://github.com/andycasey/ads/blob/master/ads/tests/test_export.py#L32) and [this](https://github.com/andycasey/ads/blob/master/ads/tests/test_sandbox.py#L62).

**Comment by vsudilov** [comment]
We can't control the ratelimit that ADS imposes, which indeed is 200/24hours for the "export" (ie bibtex) service -- This library should have that correctly tracked via `ads.RateLimits('ExportQuery').get_info()`

We'll look into fixing up the unexpected behaviour you're noticing via lazy-loading `ads.SearchQuery.bibtex`, though the correct solution for your use case is to use `ads.ExportQuery` as Jonny suggested.

**Comment by vsudilov** [comment]
We've got two options re the lazy-loading issue:

Special case properties corresponding to external endpoints (/export, /metrics) here https://github.com/andycasey/ads/blob/master/ads/search.py#L122

or deprecate these convenience properties directly from `SearchQuery`. I'd vote for deprecation/removal as those properties undoubtedly lead to inefficient rate limit usage for those endpoints.

**Comment by jonnybazookatone** [comment]
I have no strong preference. I like the convenience of them, but they definitely result in rate limit problems with many users. You'd no doubt break people's scripts by deprecating them.

If the edge cases don't grow, option 1 might not be a pain to maintain.

**Comment by lowderchris** [comment]
Fantastic! I initially was testing the waters with a small list of two bibcodes, before (hastily) jumping to my test of 200. I didn't realize the separate limits for export queries, my bad.

I figured there would be a better way of structuring the request than my rather clunky method; Thanks for the suggestion! I had initially written the script to be usable on a single paper basis from the command line, and then quickly adapted it to read an input database of bibcodes. I'll rewrite and test that script once my rate limit resets tomorrow.
